### PR TITLE
Trying to add past events to AWM page

### PR DESCRIPTION
**Pull request by ghseeli**
## Will this code work?

I am trying to add the past events to the AWM page, but I cannot test it locally for some reason; I think the Google calendar API does not let my computer access the calendar. 

## Will this solution work? 

I know other seminars do a thing where they list previous events year by year, but AWM is not like a normal seminar, and so I was thinking it would be simpler to just have a bunch of the past events listed on the main page. Maybe for really far back past events, I could add a separate page.

### CODE REVIEW

**Comment by lenis2000** [comment]
merged, see if this works

**Comment by lenis2000** [comment]
So, the code does not seem to work by the way.

If you're testing locally at localhost:4000, in chrome it should work btw

**Comment by lenis2000** [comment]
ok I'm going to add a separate page for past events. 
Having two javascript calendars on one page is bad - variables clash, simple as that

**Comment by lenis2000** [comment]
it all works now

**Comment by ghseeli** [comment]
Great! Thank you!!

**Pull request merged**
