### PR TITLE
Added REU/Internship Blog Post

### PR DESCRIPTION
**Pull request by sp6hr**
Blog post is ready, please check over the image syntax for the second image in the blog post.

### CODE REVIEW

**Comment by lenis2000** [comment]
Let me know when I should merge this. The blog post seems incomplete at this point

**Comment by ghseeli** [comment]
Yeah, I was showing @sp6hr and @ajkobin the workflow for getting a blog post made and merged in, but we ran out of time before @sp6hr could finish the blog post. We will make sure you are notified when it is complete!

**Comment by sp6hr** [comment]
After we met, I finished the blog so it should be ready to merge now. Let me know if you have further concerns.

**Comment by lenis2000** [comment]
Ok let's try to merge

**Comment by lenis2000** [comment]
@sp6hr @ghseeli 
the format for image addresses is different than what was used locally; please review 

https://github.com/uva-math/uva-math-code/commit/d761e2a624e1e2308d06141dd239faa23c6f8960

**Comment by ghseeli** [comment]
Okay, great! Thank you @lenis2000 !

**Pull request merged**
