### PR TITLE
Create 19-20

### PR DESCRIPTION
**Pull request by valiagaz**

### CODE REVIEW

**Comment by lenis2000** [comment]
Sure it’s possible to change contacts. Will figure all out tomorrow

**Comment by valiagaz** [comment]
Okay! No rush. Thanks!

________________________________

**Comment by lenis2000** [comment]
Will add this page myself (should be a little different naming of the file, for convenience)

**Comment by valiagaz** [comment]
Thank you very much!

So should email you the title/abstract every week? Or is there a way that we update the seminar website?

________________________________

**Comment by lenis2000** [comment]
There is a google calendar, what is your google calendar email?


On August 21, 2019 at 12:37:40 PM, valiagaz (notifications@github.com)
wrote:

Thank you very much!

So should email you the title/abstract every week? Or is there a way that
we update the seminar website?

________________________________

**Comment by valiagaz** [comment]
Can I use my personal gmail for this? It's valiagaz@gmail.com

________________________________

**Comment by lenis2000** [comment]
Yes, sure. Will add you to editors of the math club calendar. You just
update the calendar, and the talks will appear. Think Ben also has access.


Best,

Leonid


On August 21, 2019 at 12:49:17 PM, valiagaz (notifications@github.com)
wrote:

Can I use my personal gmail for this? It's valiagaz@gmail.com

________________________________

**Comment by valiagaz** [comment]
Great! Thanks so much! Ben and I will also be in charge of the AWM chapter this semester. Could you add me there too?

________________________________

**Comment by lenis2000** [comment]
Actually, Ben does not have access, but I just invited you.


Btw this email conversation about GitHub is publicly posted there, just so
you’re aware


On August 21, 2019 at 12:49:17 PM, valiagaz (notifications@github.com)
wrote:

Can I use my personal gmail for this? It's valiagaz@gmail.com

________________________________

**Comment by lenis2000** [comment]
I don’t have access to AWM, please ask Sara


On August 21, 2019 at 12:49:17 PM, valiagaz (notifications@github.com)
wrote:

Can I use my personal gmail for this? It's valiagaz@gmail.com

________________________________

**Comment by valiagaz** [comment]
Thanks a lot! I got the invitation and already posted the first event. I will email Sara about AWM.


Best wishes,

Valia

________________________________

**Pull request closed without merging**
