### PR TITLE
Create eg4va.md

### PR DESCRIPTION
**Pull request by valiagaz**

### CODE REVIEW

**Comment by lenis2000** [comment]
I added the link to http://www-personal.umich.edu/~gazaki/research.html to the page

**Comment by valiagaz** [comment]
Hi,


I'm sorry, I think I gave you the wrong link. Could you add http://www-personal.umich.edu/~gazaki/index.html instead?

Also, I still cannot see my page on  http://people.virginia.edu/~eg4va/. Am I doing something wrong?


Thank you again.


Best,

Valia


Homepage of Evangelia Gazaki - University of Michigan<http://www-personal.umich.edu/~gazaki/index.html>
www-personal.umich.edu
I am currently a third year Postdoctoral Assistant Professor at the University of Michigan.My mentor is Bhargav Bhatt.I completed my Ph.D. degree in mathematics in June 2016 at the University of Chicago Math under the supervision of Pr. Kazuya Kato. I received a B.A. and M.S. degree from the National and Kapodistrian University of Athens.. I am interested in arithmetic geometry and more ...

________________________________

**Comment by lenis2000** [comment]
no, it all is good but I'm having technical issues (a coincidence...) The page will be up by tomorrow

**Comment by valiagaz** [comment]
Okay! Thank you so much!

________________________________

**Comment by lenis2000** [comment]
ok it's up. I can also use your photo from the website on the UVA one, should I do that?

**Comment by valiagaz** [comment]
Sure! Thanks so much!

________________________________

**Comment by valiagaz** [comment]
Sorry, I have one more question. Currently my personal website uses my previous affiliation, university of Michigan. I see that other faculty members have a personal website of the form http://faculty.virginia.edu/huneke/. Is there a way I can make this change myself? I know you said you don't support personal websites. Is this something I need to do myself?


Thanks again and sorry for the many questions.


Best,

Valia

Craig Huneke, Marvin Rosenblum Professor of Mathematics<http://faculty.virginia.edu/huneke/>
faculty.virginia.edu
Mathematics Department University of Virginia Kerchof Hall 231 (434) 924-4946 Fax:(434) 982-3084 Email: huneke @virginia.edu

________________________________

**Comment by lenis2000** [comment]
no worries, the UVA it system is complicated and always changing... see here https://virginia.service-now.com/its?id=itsweb_kb_article&sys_id=831af530db11db404f32fb671d9619ec

**Comment by valiagaz** [comment]
Thanks again! I put on a request for a uva website. I hope I can figure that out. I just pulled another request for mathclub. This year it will be Benjamin Hayes and me who will be in charge of matahclub. Is it possible for me to be added as a contact?

________________________________

**Pull request merged**
